// Updated macro definitions as per the values from tray_menu.h

#define CLOCK_IDM_TIMER_PAUSE_RESUME 158
#define CLOCK_IDM_TIMER_RESTART 177
#define CLOCK_IDM_SLEEP 125
#define CLOCK_IDM_TIME_FORMAT_ZERO_PADDED 196
#define CLOCK_IDM_TIME_FORMAT_FULL_PADDED 197
#define CLOCK_IDM_TIME_FORMAT_SHOW_MILLISECONDS 198
#define CLOCK_IDM_ANIMATIONS_BASE 3000
#define CLOCK_IDM_ANIMATIONS_USE_LOGO 2202
#define CLOCK_IDM_ANIMATIONS_USE_CPU 2203
#define CLOCK_IDM_ANIMATIONS_USE_MEM 2204
#define CLOCK_IDM_ANIMATIONS_OPEN_DIR 2201
#define CLOCK_IDM_ANIM_SPEED_MEMORY 2210
#define CLOCK_IDM_ANIM_SPEED_CPU 2211
#define CLOCK_IDM_ANIM_SPEED_TIMER 2212
#define CLOCK_IDM_WHITE_NOISE_TOGGLE 221
#define CLOCK_IDM_WHITE_NOISE_RAIN 222
#define CLOCK_IDM_WHITE_NOISE_WIND 223
#define CLOCK_IDM_WHITE_NOISE_COFFEE 224
#define CLOCK_IDM_WHITE_NOISE_FOREST 225
#define CLOCK_IDM_WHITE_NOISE_OCEAN 226
#define CLOCK_IDM_WHITE_NOISE_VOLUME_PLUS 227
#define CLOCK_IDM_WHITE_NOISE_VOLUME_MINUS 228
#define CLOCK_IDM_WHITE_NOISE_STOP 229
